blank_issues_enabled: true
contact_links:
  - name: ❓ Discord Support
    url: https://discord.gg/PgSXZT37JV
    about: If you need help or support, visit Discord!
  - name: 📖 Documentation
    url: https://github.com/UltraCosmetics/UltraCosmetics/wiki
    about: Read the documentation.
